# Logging settings.
logging:
  level:
    org.springframework.data: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: me
    password: 123
    jdbc-url: jdbc:mysql://localhost:3306/person?serverTimezone=Europe/Paris
